networks:
  jin-net:
    external: true

services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade
    restart: unless-stopped
    volumes:
      - ./nfi/user_data:/freqtrade/user_data
      - ./nfi/configs:/freqtrade/configs
      - ./nfi/NostalgiaForInfinityX7.py:/freqtrade/NostalgiaForInfinityX7.py:ro
    env_file:
      - .env
    networks:
      - default
      - jin-net
    command: >
      trade
      --strategy-path .
      --logfile user_data/logs/freqtrade.log
